I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 209, in script
    tmmk2 tmmk3 "Ok ok"
Exception: Say has image attributes (u'tmmk3',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 209, in script
    tmmk2 tmmk3 "Ok ok"
  File "renpy/ast.py", line 715, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1384, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1108, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "renpy/character.py", line 951, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "renpy/character.py", line 877, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes (u'tmmk3',), but there's no image tag associated with the speaking character.

Windows-10-10.0.17763
Ren'Py 7.4.2.1292
SchoolDayz 1.0
Mon May 31 10:44:45 2021
